### ISSUE TITLE
support for additional stopPlaceType

### ISSUE THREAD

**Issue by Slusep** [Informatievlaanderen/OSLOthema-mobiliteitDienstregelingEnPlanning#10]
In the StopPlaces model
https://purl.eu/doc/applicationprofile/netex-belgium/stopplaces-ap/
one of the properties of the StopPlace is stopPlaceType
[stop place type](https://purl.eu/ns/mobility/timetables-and-planning#stopPlaceType)
that's an enumeration list and I suggest to support

busTerminal
trainTerminal
metroTerminal
tramTerminal
especially in light of supporting deadruns

**Comment by GeertThijs** [comment]
The enumerations in the diagram are for illustrative purposes only. The definitive lists should be decided upon at implementation. A skos:Conceptscheme should be made then with all the necessary skos:Concepts. This is because: 1) enumerations are simple lists, conceptschemes can be hierarchic and more 2) codelists should be expandable seperately from the model (so that the model should not be changed every time a value is added to the list).

**Comment by Slusep** [comment]
OK make sense, thanks for clarifying closing
