### ISSUE TITLE
support for safety and security regulation

### ISSUE THREAD

**Issue by Slusep** [Informatievlaanderen/OSLOthema-mobiliteitDienstregelingEnPlanning#11]
In order to support safety and security regulations bus operators have defined weather plans (see for example)
https://www.letec.be/News/Detail/17587 for each line
wich support 4 levels of weather conditions (1-2-3-4) and level 2 is even broken in several sublevels
althrough we are dealing with a static model, bad weather might persists several days and I recommend supporting this functionality, Especially, TEC has identified alternate routes and stops served/not served for each line

**Comment by GeertThijs** [comment]
Things like weather are dynamic off course and thus not included in NETEX but rather in SIRI. But you are right that NETEX has some construct called ValidityCondition that specifies if a service runs only under certain conditions like eg icy roads in winter. Altough the names of the AP's (eg NETEX Belgium: Timetables) suggest otherwise, the models implement the EPIP profile on NETEX only, and these constructs are not included therein. Also it was a topic that was not discussed in the working groups, so it would only possible to add ValidityConditions in a next version of the model.

**Comment by skinkie** [comment]
NeTEx features the ability to define _external triggers_. For example, to introduce extra journeys to the beach once the weather would allow it. So they are in NeTEx, but activating them is dependent on an external trigger. Why it is important to have this in NeTEx and not (only) in SIRI, is because you can't make a network description in SIRI, the maximum you can do in SIRI-PT is to create a _new_ journey, based on existing infrastructure. If the Belgium profile would _exclusively_ do EPIP, you can still export these trips, since a consumer not having implemented these triggers would never see it as an available journey.

My suggestion is: if your internal data models (or better: use cases) supports these advance use cases, model and document a _custom profile_ which implements these things so you can be NeTEx native, and the transformation to another profile would just be a filter.

**Comment by nicocelen** [comment]
Since the Belgian NeTEx application profiles are based on NeTEx EPIP with no support for validity conditions and because it was not discussed in the working groups, I would like to suggest to focus on simplicity first in an initial version. It could be considered at a later moment in time to add this in a future version.

**Comment by Slusep** [comment]
Thanks for commenting. We are in agreement. closing
