### ISSUE TITLE
geometry

### ISSUE THREAD

**Issue by Slusep** [Informatievlaanderen/OSLOthema-mobiliteitDienstregelingEnPlanning#15]
http://www.w3.org/ns/locn#Geometry

Description
    Shape and position characteristics of an object.
Usage
    Describes these features using points, lines, polygons, and coordinates.
Properties
    we have defined the following properties for this datatype: [gml](https://purl.eu/doc/applicationprofile/netex-belgium/vehiclescheduling-ap/#Geometry%3Agml), [wkt](https://purl.eu/doc/applicationprofile/netex-belgium/vehiclescheduling-ap/#Geometry%3Awkt).

-) Shoudn't we want to support geojson as well?

**Comment by GeertThijs** [comment]
You do not need to convert your data. The model does not impose any Coordinate Reference System (CRS) unlike GeoJSON does. In stead it requires you to specify the CRS that is used, in the case of WGS84 that would look like this (example of a Point geometry):

```
{
	"@type": "http://www.opengis.net/ont/sf#Point",
	"http://www.opengis.net/ont/geosparql#asGML": {
		"@value": "<gml:Point srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
                           <gml:coordinates>51.2178744,3.229362</gml:coordinates><gml:Point>",
		"@type": "http://www.opengis.net/ont/geosparql#gmlliteral"
	}
}
```
Comments:

- As you can see the CRS is mentioned in de gml-string that serialises the geometry: http://www.opengis.net/def/crs/EPSG/0/4326 is a reference to the description of WGS84.
- In this description you can see that WGS84 is a geographic coordinate system so the coordinates will be geographic (latitude, longitude).
- In that manner the geographic data documents itself (it becomes so called smart data), rather than it is some agreement written in some specification detached from the data itself.
- Data in other CRS's can be exchanged in that way, eg in Belgium chances are great that Lambert 72/50 is used, which is a cartographic coordinate system, the coordinates are xy-coordinate pairs.
- Conversion of data does not go away by using WGS84, especially in Europe. As a result of the origing lying in the US and continental drift, coordinates in Europe have to be regurlary updated. 
- It is true that GeoJSON would look cleaner as it is not some hybrid of JSON and xml, but I do not know of a version of GeoJSON where the geographic data describes its CRS.
- Lastly: GeoJSON supports not all existing types of geometry (Point, LineString, Polygon, MultiPoint, MultiLineString, MultiPolygon, and GeometryCollection), but it is true that you probably would need no other.

By the way, the GeoJSON of the example above would look like this, not that different:
````
{
	"@type": "https://purl.org/geojson/vocab#Feature",
	"https://purl.org/geojson/vocab#geometry": {
		"@type": "https://purl.org/geojson/vocab#geometry:Point",
		"https://purl.org/geojson/vocab#geometry:coordinates": [
			51.2178744,
			3.229362
		]
	}
}
````

**Comment by Slusep** [comment]
the latest spécifications for GML
https://datatracker.ietf.org/doc/html/rfc7946
especially the CRS section 
https://datatracker.ietf.org/doc/html/rfc7946#page-12
and the following note (copied from the document )
_

Note: the use of alternative coordinate reference systems was
   specified in [[GJ2008](https://datatracker.ietf.org/doc/html/rfc7946#ref-GJ2008)], but it has been removed from this version of
   the specification because the use of different coordinate reference
   systems -- especially in the manner specified in [[GJ2008](https://datatracker.ietf.org/doc/html/rfc7946#ref-GJ2008)] -- has
   proven to have interoperability issues.  In general, GeoJSON
   processing software is not expected to have access to coordinate
   reference system databases or to have network access to coordinate
   reference system transformation parameters.  However, where all
   involved parties have a prior arrangement, alternative coordinate
   reference systems can be used without risk of data being
   misinterpreted.

_

indicates that indeed CRS is not supported anymore. 
It seems to me a sufficient reason to accept your note and reject my comment. Closing the issue
